[package]
name = "project-http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.7"
crossterm = "0.23.2"
thiserror = "1.0.31"
tui = "0.18.0"
